//! Tests for the ArbiScore v2 credit model.
//!
//! The cross-implementation test replays vectors generated by the TypeScript reference
//! (contracts/test_vectors/score_vectors.txt) and requires bit-for-bit identical scores.

use arbiscore_engine::scoring::*;

const NOW: u64 = 1_790_000_000;

fn parse_vectors() -> Vec<(u16, u64, u64, u64, u64, Vec<LoanEntry>)> {
    let text = std::fs::read_to_string("../test_vectors/score_vectors.txt")
        .expect("run gen_score_vectors.ts to create test vectors");
    text.lines()
        .filter(|l| !l.trim().is_empty())
        .map(|line| {
            let (head, loans) = line.split_once('|').unwrap();
            let h: Vec<&str> = head.split_whitespace().collect();
            let vol: u128 = h[3].parse().unwrap();
            let loans = loans
                .split(';')
                .filter(|s| !s.is_empty())
                .map(|l| {
                    let f: Vec<u64> = l.split(',').map(|x| x.parse().unwrap()).collect();
                    LoanEntry { amount_usd: f[0], borrow_ts: f[1], due_ts: f[2], close_ts: f[3], status: f[4] as u8 }
                })
                .collect();
            (
                h[0].parse().unwrap(),
                h[1].parse().unwrap(),
                h[2].parse().unwrap(),
                vol.min(u64::MAX as u128) as u64,
                h[4].parse().unwrap(),
                loans,
            )
        })
        .collect()
}

#[test]
fn matches_typescript_reference_vectors() {
    let vectors = parse_vectors();
    assert!(vectors.len() > 400);
    for (i, (expected, first, txs, vol, now, loans)) in vectors.iter().enumerate() {
        let got = compute_score(*first, *txs, *vol, loans, *now);
        assert_eq!(got, *expected, "vector {} mismatch", i);
    }
}

#[test]
fn personas_land_in_intended_tiers() {
    let v = parse_vectors();
    assert_eq!(score_to_tier(v[0].0).0, RiskTier::Prime as u8, "Alice");
    assert_eq!(score_to_tier(v[1].0).0, RiskTier::Subprime as u8, "Bob");
    assert_eq!(score_to_tier(v[2].0).0, RiskTier::Moderate as u8, "Charlie");
}

#[test]
fn fresh_wallet_is_subprime_so_wallet_hopping_never_helps() {
    for age in [0u32, 1, 7, 30] {
        let s = compute_score(NOW - age as u64 * DAY, age as u64, 100, &[], NOW);
        assert!(s < 600, "fresh wallet (age {age}d) scored {s}");
    }
}

#[test]
fn repayment_raises_score_and_liquidation_lowers_it() {
    let open = spec_to_entry(5_000, 15, LOAN_OPEN, 0, NOW);
    let base = [spec_to_entry(800, 80, LOAN_REPAID, 0, NOW)];
    let with_open = compute_score(NOW - 120 * DAY, 55, 5_500, &[base[0], open], NOW);
    let repaid = compute_score(NOW - 120 * DAY, 55, 5_500, &[base[0], spec_to_entry(5_000, 15, LOAN_REPAID, 0, NOW)], NOW);
    let liquidated = compute_score(NOW - 120 * DAY, 55, 5_500, &[base[0], spec_to_entry(5_000, 15, LOAN_LIQUIDATED, 0, NOW)], NOW);
    assert!(repaid > with_open && with_open > liquidated, "{repaid} > {with_open} > {liquidated}");
}

#[test]
fn late_repayment_scores_below_on_time_and_old_liquidations_fade() {
    let first = NOW - 400 * DAY;
    let on_time = compute_score(first, 50, 5_000, &[spec_to_entry(3_000, 60, LOAN_REPAID, 0, NOW)], NOW);
    let late = compute_score(first, 50, 5_000, &[spec_to_entry(3_000, 60, LOAN_REPAID, 20, NOW)], NOW);
    assert!(on_time > late);

    let recent_liq = compute_score(first, 50, 5_000, &[spec_to_entry(3_000, 60, LOAN_LIQUIDATED, 0, NOW)], NOW);
    let old_liq = compute_score(first, 50, 5_000, &[spec_to_entry(3_000, 390, LOAN_LIQUIDATED, 0, NOW)], NOW);
    assert!(old_liq > recent_liq);
}

#[test]
fn repayments_older_than_64_loans_drop_out_but_liquidations_do_not() {
    let good: Vec<LoanEntry> = (0..64).map(|i| spec_to_entry(1_000, 10 + i, LOAN_REPAID, 0, NOW)).collect();
    // Older repaid loans are outside the window and don't count
    let mut with_old_good = vec![spec_to_entry(50_000, 300, LOAN_REPAID, 0, NOW); 10];
    with_old_good.extend_from_slice(&good);
    let base = compute_score(NOW - 800 * DAY, 100, 10_000, &good, NOW);
    assert_eq!(base, compute_score(NOW - 800 * DAY, 100, 10_000, &with_old_good, NOW));
    // Older liquidations can't be buried under new loans: they still count
    let mut with_old_bad = vec![spec_to_entry(5_000, 150, LOAN_LIQUIDATED, 0, NOW); 2];
    with_old_bad.extend_from_slice(&good);
    let buried = compute_score(NOW - 800 * DAY, 100, 10_000, &with_old_bad, NOW);
    assert!(buried + 50 < base, "buried liquidations must still hurt: {base} vs {buried}");
    // Only the 16 most recent liquidations are kept outside the window (bounded gas)
    let mut many = vec![spec_to_entry(5_000, 150, LOAN_LIQUIDATED, 0, NOW); 17];
    many.extend_from_slice(&good);
    let mut sixteen = vec![spec_to_entry(5_000, 150, LOAN_LIQUIDATED, 0, NOW); 16];
    sixteen.extend_from_slice(&good);
    assert_eq!(compute_score(NOW - 800 * DAY, 100, 10_000, &many, NOW), compute_score(NOW - 800 * DAY, 100, 10_000, &sixteen, NOW));
}

#[test]
fn score_is_capped_at_subprime_while_a_loan_is_overdue() {
    let mut loans: Vec<LoanEntry> = (0..12).map(|i| spec_to_entry(10_000, 60 + 30 * i, LOAN_REPAID, 0, NOW)).collect();
    let prime = compute_score(NOW - 800 * DAY, 200, 80_000, &loans, NOW);
    assert!(prime >= 750, "setup should be Prime, got {prime}");
    loans.push(spec_to_entry(1_000, 45, LOAN_OPEN, 0, NOW)); // 15 days overdue
    let capped = compute_score(NOW - 800 * DAY, 200, 80_000, &loans, NOW);
    assert!(capped <= DEFAULT_CAP, "overdue loan must cap the score: {capped}");
}

#[test]
fn extreme_inputs_stay_in_bounds() {
    let huge = LoanEntry { amount_usd: u64::MAX, borrow_ts: 0, due_ts: 0, close_ts: u64::MAX, status: LOAN_REPAID };
    for loans in [vec![], vec![huge; 64], vec![LoanEntry { status: LOAN_LIQUIDATED, ..huge }; 64]] {
        for (first, txs, vol, now) in [(0, 0, 0, 0), (u64::MAX, u64::MAX, u64::MAX, u64::MAX), (1, u64::MAX, u64::MAX, NOW)] {
            let s = compute_score(first, txs, vol, &loans, now);
            assert!((MIN_SCORE..=MAX_SCORE).contains(&s));
        }
    }
}

#[test]
fn exp2_and_isqrt_are_accurate() {
    assert_eq!(exp2_neg(0), 1_000_000);
    assert!((exp2_neg(1_000_000) as i64 - 500_000).abs() <= 1);
    assert!((exp2_neg(500_000) as i64 - 707_107).abs() <= 2);
    assert_eq!(exp2_neg(64_000_000), 0);
    for n in [0u128, 1, 2, 3, 4, 15, 16, 17, 1_000_000, u64::MAX as u128] {
        let r = isqrt(n);
        assert!(r * r <= n && (r + 1) * (r + 1) > n, "isqrt({n}) = {r}");
    }
}

#[test]
fn tier_boundaries() {
    assert_eq!(score_to_tier(300), (0, 12500));
    assert_eq!(score_to_tier(599), (0, 12500));
    assert_eq!(score_to_tier(600), (1, 11800));
    assert_eq!(score_to_tier(679), (1, 11800));
    assert_eq!(score_to_tier(680), (2, 11200));
    assert_eq!(score_to_tier(749), (2, 11200));
    assert_eq!(score_to_tier(750), (3, 10500));
    assert_eq!(score_to_tier(850), (3, 10500));
}

#[test]
fn zero_float_opcodes_in_wasm() {
    let wasm_path = std::path::Path::new("target/arbiscore_engine.stylus.wasm");
    if !wasm_path.exists() {
        eprintln!("{wasm_path:?} not built yet (node build_wasm.mjs); skipping");
        return;
    }
    let wasm_bytes = std::fs::read(wasm_path).unwrap();
    let mut float_ops = Vec::new();
    for payload in wasmparser::Parser::new(0).parse_all(&wasm_bytes) {
        if let wasmparser::Payload::CodeSectionEntry(body) = payload.unwrap() {
            let mut reader = body.get_operators_reader().unwrap();
            while !reader.eof() {
                let op = format!("{:?}", reader.read().unwrap());
                if op.starts_with("F32") || op.starts_with("F64") {
                    float_ops.push(op);
                }
            }
        }
    }
    assert!(float_ops.is_empty(), "float instructions found: {float_ops:?}");
}

#[test]
fn instant_borrow_repay_loops_earn_no_credit() {
    let fresh = compute_score(NOW, 0, 0, &[], NOW);
    let loop_loan = LoanEntry { amount_usd: 50_000, borrow_ts: NOW, due_ts: NOW + 30 * DAY, close_ts: NOW, status: LOAN_REPAID };
    for n in [1usize, 3, 20, 64] {
        let s = compute_score(NOW, 0, 0, &vec![loop_loan; n], NOW);
        assert_eq!(s, fresh, "{n} instant loops moved the score");
        assert!(s < 600);
    }
    // Credit ramps in with time outstanding and is full after 14 days
    let held = |days: u64| {
        let l = LoanEntry { amount_usd: 5_000, borrow_ts: NOW - days * DAY, due_ts: NOW - days * DAY + 30 * DAY, close_ts: NOW, status: LOAN_REPAID };
        compute_score(NOW - 100 * DAY, 20, 2_000, &[l], NOW)
    };
    assert!(held(1) < held(7) && held(7) < held(14));
    assert_eq!(held(14), held(20));
}

#[test]
fn unpaid_overdue_loan_never_improves_the_score() {
    // Bob-like history fixed at time R; one open $2,500 loan due 18 days after R
    const R: u64 = NOW;
    let loans = [
        spec_to_entry(3_000, 190, LOAN_REPAID, 12, R),
        spec_to_entry(5_000, 160, LOAN_LIQUIDATED, 0, R),
        spec_to_entry(2_000, 130, LOAN_REPAID, 0, R),
        spec_to_entry(4_000, 95, LOAN_LIQUIDATED, 0, R),
        spec_to_entry(1_500, 60, LOAN_REPAID, 5, R),
        spec_to_entry(2_500, 12, LOAN_OPEN, 0, R),
    ];
    let first = R - 200 * DAY;
    let before_due = compute_score(first, 220, 30_000, &loans, R + 17 * DAY);
    let just_overdue = compute_score(first, 220, 30_000, &loans, R + 19 * DAY);
    assert!(just_overdue + 20 < before_due, "going overdue must hurt: {before_due} -> {just_overdue}");
    for d in (19..=400).step_by(7) {
        let s = compute_score(first, 220, 30_000, &loans, R + d * DAY);
        assert!(s < before_due, "day {d}: unpaid overdue loan scored {s}, above the pre-due {before_due}");
        assert!(score_to_tier(s).0 == score_to_tier(just_overdue).0, "day {d}: tier improved to {s} while still unpaid");
    }
}
