// Writes frontend/lib/web3/generated.ts from Hardhat artifacts:  npx hardhat compile && node scripts/exportAbis.js
const fs = require("fs");
const path = require("path");
const art = (p) => JSON.parse(fs.readFileSync(path.join(__dirname, "../artifacts/contracts", p), "utf8")).abi;
const abis = {
  ARBI_CREDIT_VAULT_ABI: art("ArbiCreditVault.sol/ArbiCreditVault.json"),
  STYLUS_ENGINE_ABI: art("interfaces/IArbiScoreEngine.sol/IArbiScoreEngine.json"),
  CREDIT_IMPORTER_ABI: art("CreditImporter.sol/CreditImporter.json"),
  PRICE_ORACLE_ABI: art("interfaces/IPriceOracle.sol/IPriceOracle.json"),
  TEST_TOKEN_ABI: art("mocks/MockERC20.sol/MockERC20.json"),
};
let out = "// Generated by contracts/lending_vault/scripts/exportAbis.js. Do not edit by hand.\n";
for (const [name, abi] of Object.entries(abis)) out += `\nexport const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n`;
const dest = path.join(__dirname, "../../../frontend/lib/web3/generated.ts");
fs.writeFileSync(dest, out);
console.log(`Wrote ${Object.keys(abis).join(", ")} to ${dest}`);
