/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT OR Apache-2.0
pragma solidity ^0.8.23;

interface IArbiScoreEngine {
    function init(address owner_addr, address vault_addr) external;

    function owner() external view returns (address);

    function vault() external view returns (address);

    function calculateScore(address user) external view returns (uint16);

    function calculate_score(address user) external view returns (uint16);

    function getTier(address user) external view returns (uint8, uint16);

    function get_tier(address user) external view returns (uint8, uint16);

    function getCollateralRatioBps(address user) external view returns (uint16);

    function get_collateral_ratio_bps(address user) external view returns (uint16);

    function getProfile(address user) external view returns (uint64,uint64,uint32,uint256,uint32,uint32,uint32,uint16,bool);

    function get_profile(address user) external view returns (uint64,uint64,uint32,uint256,uint32,uint32,uint32,uint16,bool);

    function updateRepaymentHistory(address user, bool borrowed, bool repaid, bool liquidated) external returns (bool);

    function update_repayment_history(address user, bool borrowed, bool repaid, bool liquidated) external returns (bool);

    function recordActivity(address user, uint32 tx_count, uint256 volume_usd) external returns (bool);

    function record_activity(address user, uint32 tx_count, uint256 volume_usd) external returns (bool);

    function setMockProfile(address user, uint32 age_days, uint32 tx_count, uint256 volume_usd, uint32 loans_taken, uint32 loans_repaid, uint32 liquidations) external returns (bool);

    function set_mock_profile(address user, uint32 age_days, uint32 tx_count, uint256 volume_usd, uint32 loans_taken, uint32 loans_repaid, uint32 liquidations) external returns (bool);

    error Unauthorized();

    error InvalidRepaymentCount();

    error ArithmeticOverflow();
}
